config/routes.rb
Rails.application.routes.draw do

    root 'bogs#index'

  resources :creatures, :bogs

  get '*path' => redirect('/404.html')
end

app/models/creature.rb
class Creature < ActiveRecord::Base

	validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
	validates :desc, :presence => true, length: {minimum: 2, maximum: 255}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bogs_controller.rb
class BogsController < ApplicationController

	def index

	end

	def show

	end

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
	before_action :fetch_creature, only: [:show, :update, :destroy, :edit]

	def index
		@creature = Creature.all
	end

	def creature

	end

	def new
		@creature = Creature.new
	end

	def create
		@creature = params.require(:creature).permit(:name, :desc)
	  @creature = Creature.create(@creature)

	  if @creature.save
	  	flash[:success] = "#{@creature.name} has been saved"
	  	redirect_to @creature
	  else
	  	render :action => :new
	  end
	end

	def show
		#fetch_creature
	   @search = @creature.desc
	   list = flickr.photos.search :text => @search, :sort => 'relevance'

	   @results = list.map do |photo|
	     [FlickRaw.url_m(photo),
	     FlickRaw.url_b(photo)]
	   end
	 end

	def edit
		#fetch_creature
	end

	def update
		#fetch_creature
		creature_id = params[:id]
		updated_attributes = params.require(:creature).permit(:name, :desc)

		@creature.update_attributes(updated_attributes)
		redirect_to "/creatures/#{creature_id}"

	end

	def destroy
		#fetch_creature
		@creature.destroy
		redirect_to '/creatures'
	end

	private

		def fetch_creature
			redirect_to '/404.html' unless @creature = Creature.find_by_id(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bogs/index.html.erb
<center>
	<h1>MUCH CLASS...</h1>
	<h2>many dog</h2>
<h3><%= link_to "See Our Lovely Pooches", creatures_path %></h3>


</center>

app/views/creatures/_form.html.erb
<%= form_for @creature, :html => { :class => "form-horizontal creature" } do |f| %>

    <% if @creature.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@creature.errors.count, "error") %> prohibited this creature from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @creature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@creature[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'form-control' %>
    </div>
    <%= error_span(@creature[:desc]) %>
  </div>

<br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            creatures_path, :class => 'btn btn-default' %>

<% end %>

app/views/creatures/edit.html.erb
<%- model_class = Creature -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/creatures/index.html.erb
<%- model_class = Creature -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:desc) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @creature.each do |creature| %>
      <tr>
        <td><%= link_to creature.id, creature_path(creature) %></td>
        <td><%= creature.name %></td>
        <td><%= creature.desc %></td>
        <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),edit_creature_path(creature), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),creature_path(creature),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },:class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("new dog")),new_creature_path,:class => 'btn btn-primary' %>

app/views/creatures/new.html.erb
<%- model_class = Creature -%>
<div class="page-header">
  <h1>New Pup</h1>
</div>
<br />
<%= render :partial => 'form' %>

app/views/creatures/show.html.erb
<%- model_class = Creature -%>
<% if flash.any? %>
	<% flash.each do |key,message| %>
		<div class="alert alert-<%= key %>"> <%= message %> </div>
	<%end%>
<%end%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.human_attribute_name(:name) %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @creature.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @creature.desc %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              creatures_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_creature_path(@creature), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              creature_path(@creature),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


<h1>Results <small><%= @search %></small></h1>

<% @results.each do |photo| %>
<%= link_to image_tag(photo.first), photo.last %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogAppLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dogs Forever</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
<!--         <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li> -->
            <li> <%= link_to "Home", '/'%> </li>
            <li> <%= link_to "See All Dogs", creatures_path %> </li>
            <li> <%= link_to "Create a New Dog", new_creature_path %> </li>
<!--             <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
      </ul> -->
<!--       <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-2 col-sm-6 col-sm-offset-2 heading">
			<%= yield %>
		</div>
		<div class="col-md-3 col-md-offset-1 col-sm-3 col-sm-offset-1 about-us">
			<h1>About Us</h1>
			<p>We get it. You want to make references to your colleagues and friends, describing them as dog breeds. Well, this website is for you. Label away!</p>
		</div>
	</div>
</div>
</body>
</html>